<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>14 Multivariate Regression with Dummy Variables | LBOMETR Course Book</title>
  <meta name="description" content="An introduction to the LBOMETR Course Book." />
  <meta name="generator" content="bookdown 0.41 and GitBook 2.6.7" />

  <meta property="og:title" content="14 Multivariate Regression with Dummy Variables | LBOMETR Course Book" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="An introduction to the LBOMETR Course Book." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="14 Multivariate Regression with Dummy Variables | LBOMETR Course Book" />
  
  <meta name="twitter:description" content="An introduction to the LBOMETR Course Book." />
  

<meta name="author" content="Jem Marie M. Nario" />


<meta name="date" content="2025-07-09" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="ordinary-least-squares.html"/>
<link rel="next" href="formal-tests-on-assumptions.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<h1>LBOMETR Course Book</h1>
<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Introduction</a>
<ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#about-me"><i class="fa fa-check"></i><b>1.1</b> About Me</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="syllabus.html"><a href="syllabus.html"><i class="fa fa-check"></i><b>2</b> Syllabus</a>
<ul>
<li class="chapter" data-level="2.1" data-path="syllabus.html"><a href="syllabus.html#course-information"><i class="fa fa-check"></i><b>2.1</b> Course Information</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="syllabus.html"><a href="syllabus.html#general-course-description"><i class="fa fa-check"></i><b>2.1.1</b> General Course Description</a></li>
<li class="chapter" data-level="2.1.2" data-path="syllabus.html"><a href="syllabus.html#specific-course-description"><i class="fa fa-check"></i><b>2.1.2</b> Specific Course Description</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="syllabus.html"><a href="syllabus.html#learning-goals-and-outcomes"><i class="fa fa-check"></i><b>2.2</b> Learning Goals and Outcomes</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="syllabus.html"><a href="syllabus.html#expected-lasallian-graduate-attributes-elgas"><i class="fa fa-check"></i><b>2.2.1</b> Expected Lasallian Graduate Attributes (ELGAs)</a></li>
<li class="chapter" data-level="2.2.2" data-path="syllabus.html"><a href="syllabus.html#programme-learning-outcomes-plos"><i class="fa fa-check"></i><b>2.2.2</b> Programme Learning Outcomes (PLOs)</a></li>
<li class="chapter" data-level="2.2.3" data-path="syllabus.html"><a href="syllabus.html#course-learning-outcomes-clos"><i class="fa fa-check"></i><b>2.2.3</b> Course Learning Outcomes (CLOs)</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="syllabus.html"><a href="syllabus.html#mapping-of-clos-to-elgas"><i class="fa fa-check"></i><b>2.3</b> Mapping of CLOs to ELGAs</a></li>
<li class="chapter" data-level="2.4" data-path="syllabus.html"><a href="syllabus.html#mapping-of-clos-to-plos"><i class="fa fa-check"></i><b>2.4</b> Mapping of CLOs to PLOs</a></li>
<li class="chapter" data-level="2.5" data-path="syllabus.html"><a href="syllabus.html#course-assessments"><i class="fa fa-check"></i><b>2.5</b> Course Assessments</a></li>
<li class="chapter" data-level="2.6" data-path="syllabus.html"><a href="syllabus.html#grading-system"><i class="fa fa-check"></i><b>2.6</b> Grading System</a></li>
<li class="chapter" data-level="2.7" data-path="syllabus.html"><a href="syllabus.html#class-policies"><i class="fa fa-check"></i><b>2.7</b> Class Policies</a>
<ul>
<li class="chapter" data-level="2.7.1" data-path="syllabus.html"><a href="syllabus.html#attendance"><i class="fa fa-check"></i><b>2.7.1</b> 1. Attendance</a></li>
<li class="chapter" data-level="2.7.2" data-path="syllabus.html"><a href="syllabus.html#course-materials"><i class="fa fa-check"></i><b>2.7.2</b> 2. Course Materials</a></li>
<li class="chapter" data-level="2.7.3" data-path="syllabus.html"><a href="syllabus.html#grading-notes"><i class="fa fa-check"></i><b>2.7.3</b> 3. Grading Notes</a></li>
<li class="chapter" data-level="2.7.4" data-path="syllabus.html"><a href="syllabus.html#incentives-and-extra-credit"><i class="fa fa-check"></i><b>2.7.4</b> 4. Incentives and Extra Credit</a></li>
<li class="chapter" data-level="2.7.5" data-path="syllabus.html"><a href="syllabus.html#computer-practicals"><i class="fa fa-check"></i><b>2.7.5</b> 5. Computer Practicals</a></li>
<li class="chapter" data-level="2.7.6" data-path="syllabus.html"><a href="syllabus.html#groupings-and-peer-evaluation"><i class="fa fa-check"></i><b>2.7.6</b> 6. Groupings and Peer Evaluation</a></li>
<li class="chapter" data-level="2.7.7" data-path="syllabus.html"><a href="syllabus.html#extensions"><i class="fa fa-check"></i><b>2.7.7</b> 7. Extensions</a></li>
<li class="chapter" data-level="2.7.8" data-path="syllabus.html"><a href="syllabus.html#use-of-ai-tools"><i class="fa fa-check"></i><b>2.7.8</b> 8. Use of AI Tools</a></li>
<li class="chapter" data-level="2.7.9" data-path="syllabus.html"><a href="syllabus.html#consultations"><i class="fa fa-check"></i><b>2.7.9</b> 9. Consultations</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="course-assessments-1.html"><a href="course-assessments-1.html"><i class="fa fa-check"></i><b>3</b> Course Assessments</a>
<ul>
<li class="chapter" data-level="3.1" data-path="course-assessments-1.html"><a href="course-assessments-1.html#data-story-archive"><i class="fa fa-check"></i><b>3.1</b> Data Story Archive</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="course-assessments-1.html"><a href="course-assessments-1.html#requirements"><i class="fa fa-check"></i><b>3.1.1</b> Requirements</a></li>
<li class="chapter" data-level="3.1.2" data-path="course-assessments-1.html"><a href="course-assessments-1.html#submission"><i class="fa fa-check"></i><b>3.1.2</b> Submission</a></li>
<li class="chapter" data-level="3.1.3" data-path="course-assessments-1.html"><a href="course-assessments-1.html#grading-rubric-for-data-story-archive"><i class="fa fa-check"></i><b>3.1.3</b> Grading Rubric for Data Story Archive</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="course-assessments-1.html"><a href="course-assessments-1.html#data-story-presentation"><i class="fa fa-check"></i><b>3.2</b> Data Story Presentation</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="course-assessments-1.html"><a href="course-assessments-1.html#requirements-1"><i class="fa fa-check"></i><b>3.2.1</b> Requirements</a></li>
<li class="chapter" data-level="3.2.2" data-path="course-assessments-1.html"><a href="course-assessments-1.html#grading-rubric"><i class="fa fa-check"></i><b>3.2.2</b> Grading Rubric</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="grouping-process.html"><a href="grouping-process.html"><i class="fa fa-check"></i><b>4</b> Grouping Process</a>
<ul>
<li class="chapter" data-level="4.1" data-path="grouping-process.html"><a href="grouping-process.html#how-groups-are-formed"><i class="fa fa-check"></i><b>4.1</b> How Groups Are Formed</a></li>
<li class="chapter" data-level="4.2" data-path="grouping-process.html"><a href="grouping-process.html#announcement-of-groups"><i class="fa fa-check"></i><b>4.2</b> Announcement of Groups</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="data-story-research-question.html"><a href="data-story-research-question.html"><i class="fa fa-check"></i><b>5</b> Data Story Research Question</a>
<ul>
<li class="chapter" data-level="5.1" data-path="data-story-research-question.html"><a href="data-story-research-question.html#guidelines-in-conducting-data-story"><i class="fa fa-check"></i><b>5.1</b> Guidelines in Conducting Data Story</a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="data-story-research-question.html"><a href="data-story-research-question.html#research-question"><i class="fa fa-check"></i><b>5.1.1</b> Research Question:</a></li>
<li class="chapter" data-level="5.1.2" data-path="data-story-research-question.html"><a href="data-story-research-question.html#relevance"><i class="fa fa-check"></i><b>5.1.2</b> Relevance</a></li>
<li class="chapter" data-level="5.1.3" data-path="data-story-research-question.html"><a href="data-story-research-question.html#for-the-data-story-should-i-use-kaggle"><i class="fa fa-check"></i><b>5.1.3</b> For the data story, should I use Kaggle?</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="data-story-research-question.html"><a href="data-story-research-question.html#comments-on-research-questions"><i class="fa fa-check"></i><b>5.2</b> Comments on Research Questions:</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="basic-introduction-to-r.html"><a href="basic-introduction-to-r.html"><i class="fa fa-check"></i><b>6</b> Basic Introduction to R</a>
<ul>
<li class="chapter" data-level="6.1" data-path="basic-introduction-to-r.html"><a href="basic-introduction-to-r.html#session-information"><i class="fa fa-check"></i><b>6.1</b> Session Information</a></li>
<li class="chapter" data-level="6.2" data-path="basic-introduction-to-r.html"><a href="basic-introduction-to-r.html#preliminaries"><i class="fa fa-check"></i><b>6.2</b> Preliminaries</a></li>
<li class="chapter" data-level="6.3" data-path="basic-introduction-to-r.html"><a href="basic-introduction-to-r.html#quarto-markdown"><i class="fa fa-check"></i><b>6.3</b> Quarto Markdown</a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="basic-introduction-to-r.html"><a href="basic-introduction-to-r.html#starting-a-quarto-file"><i class="fa fa-check"></i><b>6.3.1</b> 1. Starting a Quarto File</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="basic-introduction-to-r.html"><a href="basic-introduction-to-r.html#packages"><i class="fa fa-check"></i><b>6.4</b> Packages</a></li>
<li class="chapter" data-level="6.5" data-path="basic-introduction-to-r.html"><a href="basic-introduction-to-r.html#instructions-for-managing-working-directories"><i class="fa fa-check"></i><b>6.5</b> Instructions for Managing Working Directories</a>
<ul>
<li class="chapter" data-level="6.5.1" data-path="basic-introduction-to-r.html"><a href="basic-introduction-to-r.html#local-working-directory-setup"><i class="fa fa-check"></i><b>6.5.1</b> 1. Local Working Directory Setup</a></li>
<li class="chapter" data-level="6.5.2" data-path="basic-introduction-to-r.html"><a href="basic-introduction-to-r.html#file-naming-convention"><i class="fa fa-check"></i><b>6.5.2</b> 2. File Naming Convention</a></li>
<li class="chapter" data-level="6.5.3" data-path="basic-introduction-to-r.html"><a href="basic-introduction-to-r.html#shared-google-drive-setup"><i class="fa fa-check"></i><b>6.5.3</b> 3. Shared Google Drive Setup</a></li>
<li class="chapter" data-level="6.5.4" data-path="basic-introduction-to-r.html"><a href="basic-introduction-to-r.html#workflow-for-.qmd-files"><i class="fa fa-check"></i><b>6.5.4</b> 4. Workflow for <code>.qmd</code> files</a></li>
<li class="chapter" data-level="6.5.5" data-path="basic-introduction-to-r.html"><a href="basic-introduction-to-r.html#rendering-the-final-report"><i class="fa fa-check"></i><b>6.5.5</b> 5. Rendering the Final Report</a></li>
<li class="chapter" data-level="6.5.6" data-path="basic-introduction-to-r.html"><a href="basic-introduction-to-r.html#summary-workflow"><i class="fa fa-check"></i><b>6.5.6</b> Summary Workflow</a></li>
</ul></li>
<li class="chapter" data-level="6.6" data-path="basic-introduction-to-r.html"><a href="basic-introduction-to-r.html#note"><i class="fa fa-check"></i><b>6.6</b> Note:</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="data-management---cross-sectional-data.html"><a href="data-management---cross-sectional-data.html"><i class="fa fa-check"></i><b>7</b> Data Management - Cross-Sectional Data</a>
<ul>
<li class="chapter" data-level="7.1" data-path="data-management---cross-sectional-data.html"><a href="data-management---cross-sectional-data.html#where-to-get-data"><i class="fa fa-check"></i><b>7.1</b> Where to Get Data?</a></li>
<li class="chapter" data-level="7.2" data-path="data-management---cross-sectional-data.html"><a href="data-management---cross-sectional-data.html#preliminaries-1"><i class="fa fa-check"></i><b>7.2</b> Preliminaries</a>
<ul>
<li class="chapter" data-level="7.2.1" data-path="data-management---cross-sectional-data.html"><a href="data-management---cross-sectional-data.html#dataset"><i class="fa fa-check"></i><b>7.2.1</b> Dataset</a></li>
<li class="chapter" data-level="7.2.2" data-path="data-management---cross-sectional-data.html"><a href="data-management---cross-sectional-data.html#packages-1"><i class="fa fa-check"></i><b>7.2.2</b> Packages</a></li>
<li class="chapter" data-level="7.2.3" data-path="data-management---cross-sectional-data.html"><a href="data-management---cross-sectional-data.html#setting-up-the-directory"><i class="fa fa-check"></i><b>7.2.3</b> Setting up the Directory</a></li>
<li class="chapter" data-level="7.2.4" data-path="data-management---cross-sectional-data.html"><a href="data-management---cross-sectional-data.html#clean-everything"><i class="fa fa-check"></i><b>7.2.4</b> Clean Everything</a></li>
<li class="chapter" data-level="7.2.5" data-path="data-management---cross-sectional-data.html"><a href="data-management---cross-sectional-data.html#importing-the-dataset"><i class="fa fa-check"></i><b>7.2.5</b> Importing the Dataset</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="data-management---cross-sectional-data.html"><a href="data-management---cross-sectional-data.html#data-cleaning"><i class="fa fa-check"></i><b>7.3</b> Data Cleaning</a>
<ul>
<li class="chapter" data-level="7.3.1" data-path="data-management---cross-sectional-data.html"><a href="data-management---cross-sectional-data.html#renaming-the-variables"><i class="fa fa-check"></i><b>7.3.1</b> Renaming the Variables</a></li>
<li class="chapter" data-level="7.3.2" data-path="data-management---cross-sectional-data.html"><a href="data-management---cross-sectional-data.html#sorting-certain-values"><i class="fa fa-check"></i><b>7.3.2</b> Sorting certain values</a></li>
<li class="chapter" data-level="7.3.3" data-path="data-management---cross-sectional-data.html"><a href="data-management---cross-sectional-data.html#pipe-operator"><i class="fa fa-check"></i><b>7.3.3</b> Pipe Operator</a></li>
<li class="chapter" data-level="7.3.4" data-path="data-management---cross-sectional-data.html"><a href="data-management---cross-sectional-data.html#adding-columns"><i class="fa fa-check"></i><b>7.3.4</b> Adding columns</a></li>
<li class="chapter" data-level="7.3.5" data-path="data-management---cross-sectional-data.html"><a href="data-management---cross-sectional-data.html#transforming-values"><i class="fa fa-check"></i><b>7.3.5</b> Transforming values</a></li>
<li class="chapter" data-level="7.3.6" data-path="data-management---cross-sectional-data.html"><a href="data-management---cross-sectional-data.html#summarizing"><i class="fa fa-check"></i><b>7.3.6</b> Summarizing</a></li>
<li class="chapter" data-level="7.3.7" data-path="data-management---cross-sectional-data.html"><a href="data-management---cross-sectional-data.html#merging-datasets"><i class="fa fa-check"></i><b>7.3.7</b> Merging datasets</a></li>
<li class="chapter" data-level="7.3.8" data-path="data-management---cross-sectional-data.html"><a href="data-management---cross-sectional-data.html#splitting-datasets"><i class="fa fa-check"></i><b>7.3.8</b> Splitting datasets</a></li>
<li class="chapter" data-level="7.3.9" data-path="data-management---cross-sectional-data.html"><a href="data-management---cross-sectional-data.html#dates"><i class="fa fa-check"></i><b>7.3.9</b> Dates</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="data-management---cross-sectional-data.html"><a href="data-management---cross-sectional-data.html#data-management-practical"><i class="fa fa-check"></i><b>7.4</b> Data Management Practical</a></li>
<li class="chapter" data-level="7.5" data-path="data-management---cross-sectional-data.html"><a href="data-management---cross-sectional-data.html#data-management-cross-sectional-feedback"><i class="fa fa-check"></i><b>7.5</b> Data Management (Cross-Sectional) Feedback</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="data-management---time-series-and-panel-data.html"><a href="data-management---time-series-and-panel-data.html"><i class="fa fa-check"></i><b>8</b> Data Management - Time Series and Panel Data</a>
<ul>
<li class="chapter" data-level="8.1" data-path="data-management---time-series-and-panel-data.html"><a href="data-management---time-series-and-panel-data.html#topic-guide"><i class="fa fa-check"></i><b>8.1</b> Topic Guide:</a></li>
<li class="chapter" data-level="8.2" data-path="data-management---time-series-and-panel-data.html"><a href="data-management---time-series-and-panel-data.html#time-series-data"><i class="fa fa-check"></i><b>8.2</b> Time Series Data</a>
<ul>
<li class="chapter" data-level="8.2.1" data-path="data-management---time-series-and-panel-data.html"><a href="data-management---time-series-and-panel-data.html#preliminaries-2"><i class="fa fa-check"></i><b>8.2.1</b> Preliminaries</a></li>
<li class="chapter" data-level="8.2.2" data-path="data-management---time-series-and-panel-data.html"><a href="data-management---time-series-and-panel-data.html#convert-to-date-format"><i class="fa fa-check"></i><b>8.2.2</b> Convert to Date Format</a></li>
<li class="chapter" data-level="8.2.3" data-path="data-management---time-series-and-panel-data.html"><a href="data-management---time-series-and-panel-data.html#aggregate-data"><i class="fa fa-check"></i><b>8.2.3</b> Aggregate Data</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="data-management---time-series-and-panel-data.html"><a href="data-management---time-series-and-panel-data.html#modifying-long-and-wide-datasets"><i class="fa fa-check"></i><b>8.3</b> Modifying Long and Wide Datasets</a>
<ul>
<li class="chapter" data-level="8.3.1" data-path="data-management---time-series-and-panel-data.html"><a href="data-management---time-series-and-panel-data.html#how-to-determine"><i class="fa fa-check"></i><b>8.3.1</b> How to Determine</a></li>
<li class="chapter" data-level="8.3.2" data-path="data-management---time-series-and-panel-data.html"><a href="data-management---time-series-and-panel-data.html#setting-up-the-dataset"><i class="fa fa-check"></i><b>8.3.2</b> Setting up the Dataset</a></li>
</ul></li>
<li class="chapter" data-level="8.4" data-path="data-management---time-series-and-panel-data.html"><a href="data-management---time-series-and-panel-data.html#missing-values"><i class="fa fa-check"></i><b>8.4</b> Missing Values</a>
<ul>
<li class="chapter" data-level="8.4.1" data-path="data-management---time-series-and-panel-data.html"><a href="data-management---time-series-and-panel-data.html#setting-up-a-sample-dataset"><i class="fa fa-check"></i><b>8.4.1</b> Setting up a Sample Dataset</a></li>
<li class="chapter" data-level="8.4.2" data-path="data-management---time-series-and-panel-data.html"><a href="data-management---time-series-and-panel-data.html#replace-with-0"><i class="fa fa-check"></i><b>8.4.2</b> Replace with <code>0</code></a></li>
<li class="chapter" data-level="8.4.3" data-path="data-management---time-series-and-panel-data.html"><a href="data-management---time-series-and-panel-data.html#remove-rows-or-columns-with-missing-values"><i class="fa fa-check"></i><b>8.4.3</b> Remove Rows or Columns with Missing Values</a></li>
<li class="chapter" data-level="8.4.4" data-path="data-management---time-series-and-panel-data.html"><a href="data-management---time-series-and-panel-data.html#imputing-missing-values-with-the-mean"><i class="fa fa-check"></i><b>8.4.4</b> Imputing Missing Values with the Mean</a></li>
<li class="chapter" data-level="8.4.5" data-path="data-management---time-series-and-panel-data.html"><a href="data-management---time-series-and-panel-data.html#note-1"><i class="fa fa-check"></i><b>8.4.5</b> Note:</a></li>
<li class="chapter" data-level="8.4.6" data-path="data-management---time-series-and-panel-data.html"><a href="data-management---time-series-and-panel-data.html#best-practice"><i class="fa fa-check"></i><b>8.4.6</b> Best Practice:</a></li>
<li class="chapter" data-level="8.4.7" data-path="data-management---time-series-and-panel-data.html"><a href="data-management---time-series-and-panel-data.html#next-meeting"><i class="fa fa-check"></i><b>8.4.7</b> Next Meeting:</a></li>
<li class="chapter" data-level="8.4.8" data-path="data-management---time-series-and-panel-data.html"><a href="data-management---time-series-and-panel-data.html#final-note"><i class="fa fa-check"></i><b>8.4.8</b> Final Note:</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9" data-path="visualizations-using-ggplot2.html"><a href="visualizations-using-ggplot2.html"><i class="fa fa-check"></i><b>9</b> Visualizations using ggplot2</a>
<ul>
<li class="chapter" data-level="9.1" data-path="visualizations-using-ggplot2.html"><a href="visualizations-using-ggplot2.html#preliminaries-3"><i class="fa fa-check"></i><b>9.1</b> Preliminaries</a>
<ul>
<li class="chapter" data-level="9.1.1" data-path="visualizations-using-ggplot2.html"><a href="visualizations-using-ggplot2.html#load-the-dataset"><i class="fa fa-check"></i><b>9.1.1</b> Load the dataset</a></li>
<li class="chapter" data-level="9.1.2" data-path="visualizations-using-ggplot2.html"><a href="visualizations-using-ggplot2.html#template"><i class="fa fa-check"></i><b>9.1.2</b> Template</a></li>
</ul></li>
<li class="chapter" data-level="9.2" data-path="visualizations-using-ggplot2.html"><a href="visualizations-using-ggplot2.html#visualizing-data-using-geom"><i class="fa fa-check"></i><b>9.2</b> Visualizing Data using <code>geom</code></a>
<ul>
<li class="chapter" data-level="9.2.1" data-path="visualizations-using-ggplot2.html"><a href="visualizations-using-ggplot2.html#scatterplots"><i class="fa fa-check"></i><b>9.2.1</b> Scatterplots</a></li>
<li class="chapter" data-level="9.2.2" data-path="visualizations-using-ggplot2.html"><a href="visualizations-using-ggplot2.html#boxplots"><i class="fa fa-check"></i><b>9.2.2</b> Boxplots</a></li>
<li class="chapter" data-level="9.2.3" data-path="visualizations-using-ggplot2.html"><a href="visualizations-using-ggplot2.html#bar-plots"><i class="fa fa-check"></i><b>9.2.3</b> Bar plots</a></li>
<li class="chapter" data-level="9.2.4" data-path="visualizations-using-ggplot2.html"><a href="visualizations-using-ggplot2.html#faceting"><i class="fa fa-check"></i><b>9.2.4</b> Faceting</a></li>
<li class="chapter" data-level="9.2.5" data-path="visualizations-using-ggplot2.html"><a href="visualizations-using-ggplot2.html#pie-chart"><i class="fa fa-check"></i><b>9.2.5</b> Pie Chart</a></li>
<li class="chapter" data-level="9.2.6" data-path="visualizations-using-ggplot2.html"><a href="visualizations-using-ggplot2.html#histogram"><i class="fa fa-check"></i><b>9.2.6</b> Histogram</a></li>
</ul></li>
<li class="chapter" data-level="9.3" data-path="visualizations-using-ggplot2.html"><a href="visualizations-using-ggplot2.html#visualizing-time-series-data"><i class="fa fa-check"></i><b>9.3</b> Visualizing Time Series Data</a></li>
<li class="chapter" data-level="9.4" data-path="visualizations-using-ggplot2.html"><a href="visualizations-using-ggplot2.html#practical-visualizations"><i class="fa fa-check"></i><b>9.4</b> Practical: Visualizations</a></li>
<li class="chapter" data-level="9.5" data-path="visualizations-using-ggplot2.html"><a href="visualizations-using-ggplot2.html#feedback-practical-visualizations"><i class="fa fa-check"></i><b>9.5</b> Feedback: Practical Visualizations</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="advanced-visualizations.html"><a href="advanced-visualizations.html"><i class="fa fa-check"></i><b>10</b> Advanced Visualizations</a>
<ul>
<li class="chapter" data-level="10.1" data-path="advanced-visualizations.html"><a href="advanced-visualizations.html#preliminaries-4"><i class="fa fa-check"></i><b>10.1</b> Preliminaries</a>
<ul>
<li class="chapter" data-level="10.1.1" data-path="advanced-visualizations.html"><a href="advanced-visualizations.html#install-packages"><i class="fa fa-check"></i><b>10.1.1</b> Install Packages</a></li>
</ul></li>
<li class="chapter" data-level="10.2" data-path="advanced-visualizations.html"><a href="advanced-visualizations.html#animated-visualizations"><i class="fa fa-check"></i><b>10.2</b> Animated Visualizations</a>
<ul>
<li class="chapter" data-level="10.2.1" data-path="advanced-visualizations.html"><a href="advanced-visualizations.html#animated-bar-chart"><i class="fa fa-check"></i><b>10.2.1</b> Animated Bar Chart</a></li>
<li class="chapter" data-level="10.2.2" data-path="advanced-visualizations.html"><a href="advanced-visualizations.html#animated-scatter-plot"><i class="fa fa-check"></i><b>10.2.2</b> Animated Scatter Plot</a></li>
<li class="chapter" data-level="10.2.3" data-path="advanced-visualizations.html"><a href="advanced-visualizations.html#animated-faceted-scatter-plot"><i class="fa fa-check"></i><b>10.2.3</b> Animated Faceted Scatter Plot</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="advanced-visualizations.html"><a href="advanced-visualizations.html#animated-time-series"><i class="fa fa-check"></i><b>10.3</b> Animated Time Series</a></li>
<li class="chapter" data-level="10.4" data-path="advanced-visualizations.html"><a href="advanced-visualizations.html#animated-faceted-time-series"><i class="fa fa-check"></i><b>10.4</b> Animated Faceted Time Series</a>
<ul>
<li class="chapter" data-level="10.4.1" data-path="advanced-visualizations.html"><a href="advanced-visualizations.html#saving-in-quarto"><i class="fa fa-check"></i><b>10.4.1</b> Saving in Quarto</a></li>
</ul></li>
<li class="chapter" data-level="10.5" data-path="advanced-visualizations.html"><a href="advanced-visualizations.html#maps"><i class="fa fa-check"></i><b>10.5</b> Maps</a>
<ul>
<li class="chapter" data-level="10.5.1" data-path="advanced-visualizations.html"><a href="advanced-visualizations.html#where-to-get-shapefiles"><i class="fa fa-check"></i><b>10.5.1</b> Where to get shapefiles?</a></li>
</ul></li>
<li class="chapter" data-level="10.6" data-path="advanced-visualizations.html"><a href="advanced-visualizations.html#static-maps"><i class="fa fa-check"></i><b>10.6</b> Static Maps</a>
<ul>
<li class="chapter" data-level="10.6.1" data-path="advanced-visualizations.html"><a href="advanced-visualizations.html#fetching-gdp-data-from-wdi"><i class="fa fa-check"></i><b>10.6.1</b> Fetching GDP Data from WDI</a></li>
</ul></li>
<li class="chapter" data-level="10.7" data-path="advanced-visualizations.html"><a href="advanced-visualizations.html#philippine-regional-map"><i class="fa fa-check"></i><b>10.7</b> Philippine Regional Map</a></li>
<li class="chapter" data-level="10.8" data-path="advanced-visualizations.html"><a href="advanced-visualizations.html#animated-map"><i class="fa fa-check"></i><b>10.8</b> Animated Map</a></li>
<li class="chapter" data-level="10.9" data-path="advanced-visualizations.html"><a href="advanced-visualizations.html#practical-advanced-visualizations"><i class="fa fa-check"></i><b>10.9</b> Practical: Advanced Visualizations</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html"><i class="fa fa-check"></i><b>11</b> Descriptive Statistics</a>
<ul>
<li class="chapter" data-level="11.1" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#preliminaries-5"><i class="fa fa-check"></i><b>11.1</b> Preliminaries</a>
<ul>
<li class="chapter" data-level="11.1.1" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#install-packages-1"><i class="fa fa-check"></i><b>11.1.1</b> Install Packages</a></li>
<li class="chapter" data-level="11.1.2" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#load-the-dataset-1"><i class="fa fa-check"></i><b>11.1.2</b> Load the dataset</a></li>
</ul></li>
<li class="chapter" data-level="11.2" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#frequency-table"><i class="fa fa-check"></i><b>11.2</b> Frequency Table</a>
<ul>
<li class="chapter" data-level="11.2.1" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#male"><i class="fa fa-check"></i><b>11.2.1</b> Male</a></li>
</ul></li>
<li class="chapter" data-level="11.3" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#histogram-1"><i class="fa fa-check"></i><b>11.3</b> Histogram</a></li>
<li class="chapter" data-level="11.4" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#summary-table"><i class="fa fa-check"></i><b>11.4</b> Summary Table</a></li>
<li class="chapter" data-level="11.5" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#interpretation-of-descriptive-statistics"><i class="fa fa-check"></i><b>11.5</b> Interpretation of Descriptive Statistics:</a>
<ul>
<li class="chapter" data-level="11.5.1" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#key-components-of-descriptive-statistics"><i class="fa fa-check"></i><b>11.5.1</b> <strong>Key Components of Descriptive Statistics</strong></a></li>
<li class="chapter" data-level="11.5.2" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#when-to-use-mean-or-median"><i class="fa fa-check"></i><b>11.5.2</b> <strong>When to Use Mean or Median</strong></a></li>
<li class="chapter" data-level="11.5.3" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#purpose-of-descriptive-statistics"><i class="fa fa-check"></i><b>11.5.3</b> <strong>Purpose of Descriptive Statistics</strong></a></li>
<li class="chapter" data-level="11.5.4" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#limitations"><i class="fa fa-check"></i><b>11.5.4</b> <strong>Limitations</strong></a></li>
</ul></li>
<li class="chapter" data-level="11.6" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#practical-descriptive-statistics"><i class="fa fa-check"></i><b>11.6</b> Practical: Descriptive Statistics</a>
<ul>
<li class="chapter" data-level="11.6.1" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#descriptive-statistics-questions"><i class="fa fa-check"></i><b>11.6.1</b> <strong>Descriptive Statistics Questions</strong></a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="12" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html"><i class="fa fa-check"></i><b>12</b> Hypothesis Testing</a>
<ul>
<li class="chapter" data-level="12.1" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#steps-1"><i class="fa fa-check"></i><b>12.1</b> Steps:</a></li>
<li class="chapter" data-level="12.2" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#difference-between-one-tailed-test-and-two-tailed-test"><i class="fa fa-check"></i><b>12.2</b> Difference between one-tailed test and two-tailed test</a>
<ul>
<li class="chapter" data-level="12.2.1" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#deciding-between-one-tailed-versus-two-tailed"><i class="fa fa-check"></i><b>12.2.1</b> Deciding between One-Tailed versus Two-Tailed</a></li>
</ul></li>
<li class="chapter" data-level="12.3" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#test-of-proportions"><i class="fa fa-check"></i><b>12.3</b> Test of Proportions</a>
<ul>
<li class="chapter" data-level="12.3.1" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#one-sample-test-of-proportion"><i class="fa fa-check"></i><b>12.3.1</b> <strong>One-Sample Test of Proportion</strong></a></li>
<li class="chapter" data-level="12.3.2" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#two-sample-test-of-proportion"><i class="fa fa-check"></i><b>12.3.2</b> <strong>Two-Sample Test of Proportion</strong></a></li>
<li class="chapter" data-level="12.3.3" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#real-world-example"><i class="fa fa-check"></i><b>12.3.3</b> Real-World Example:</a></li>
</ul></li>
<li class="chapter" data-level="12.4" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#t-tests"><i class="fa fa-check"></i><b>12.4</b> T-Tests</a>
<ul>
<li class="chapter" data-level="12.4.1" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#one-sample-t-test"><i class="fa fa-check"></i><b>12.4.1</b> One-Sample T-Test</a></li>
<li class="chapter" data-level="12.4.2" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#real-world-example-1"><i class="fa fa-check"></i><b>12.4.2</b> Real-World Example</a></li>
<li class="chapter" data-level="12.4.3" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#independent-samples-t-test"><i class="fa fa-check"></i><b>12.4.3</b> Independent-Samples T-Test</a></li>
<li class="chapter" data-level="12.4.4" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#real-world-example-2"><i class="fa fa-check"></i><b>12.4.4</b> Real-World Example</a></li>
<li class="chapter" data-level="12.4.5" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#paired-samples-t-test"><i class="fa fa-check"></i><b>12.4.5</b> Paired-Samples T-Test</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="13" data-path="ordinary-least-squares.html"><a href="ordinary-least-squares.html"><i class="fa fa-check"></i><b>13</b> Ordinary Least Squares</a>
<ul>
<li class="chapter" data-level="13.1" data-path="ordinary-least-squares.html"><a href="ordinary-least-squares.html#general-description-and-notation-of-a-linear-regression"><i class="fa fa-check"></i><b>13.1</b> <strong>General Description and notation of a Linear Regression</strong></a>
<ul>
<li class="chapter" data-level="13.1.1" data-path="ordinary-least-squares.html"><a href="ordinary-least-squares.html#the-notation"><i class="fa fa-check"></i><b>13.1.1</b> The notation</a></li>
</ul></li>
<li class="chapter" data-level="13.2" data-path="ordinary-least-squares.html"><a href="ordinary-least-squares.html#running-and-reporting-ols-regression"><i class="fa fa-check"></i><b>13.2</b> <strong>Running and reporting OLS Regression</strong></a></li>
<li class="chapter" data-level="13.3" data-path="ordinary-least-squares.html"><a href="ordinary-least-squares.html#interpretation-of-coefficients"><i class="fa fa-check"></i><b>13.3</b> <strong>Interpretation of Coefficients</strong></a></li>
<li class="chapter" data-level="13.4" data-path="ordinary-least-squares.html"><a href="ordinary-least-squares.html#goodness-of-fit-f-statistics-and-adjusted-r-squared"><i class="fa fa-check"></i><b>13.4</b> <strong>Goodness of Fit (F-Statistics and Adjusted R-squared)</strong></a></li>
<li class="chapter" data-level="13.5" data-path="ordinary-least-squares.html"><a href="ordinary-least-squares.html#assumption-diagnostics"><i class="fa fa-check"></i><b>13.5</b> <strong>Assumption Diagnostics</strong></a></li>
<li class="chapter" data-level="13.6" data-path="ordinary-least-squares.html"><a href="ordinary-least-squares.html#real-world-example-3"><i class="fa fa-check"></i><b>13.6</b> Real-World Example</a></li>
<li class="chapter" data-level="13.7" data-path="ordinary-least-squares.html"><a href="ordinary-least-squares.html#practical-hypothesis-testing-and-ols"><i class="fa fa-check"></i><b>13.7</b> Practical: Hypothesis Testing and OLS</a></li>
<li class="chapter" data-level="13.8" data-path="ordinary-least-squares.html"><a href="ordinary-least-squares.html#hypothesis-testing-1"><i class="fa fa-check"></i><b>13.8</b> Hypothesis Testing</a></li>
<li class="chapter" data-level="13.9" data-path="ordinary-least-squares.html"><a href="ordinary-least-squares.html#ols"><i class="fa fa-check"></i><b>13.9</b> OLS</a></li>
</ul></li>
<li class="chapter" data-level="14" data-path="multivariate-regression-with-dummy-variables.html"><a href="multivariate-regression-with-dummy-variables.html"><i class="fa fa-check"></i><b>14</b> Multivariate Regression with Dummy Variables</a>
<ul>
<li class="chapter" data-level="14.1" data-path="multivariate-regression-with-dummy-variables.html"><a href="multivariate-regression-with-dummy-variables.html#dummy-variables"><i class="fa fa-check"></i><b>14.1</b> Dummy Variables</a>
<ul>
<li class="chapter" data-level="14.1.1" data-path="multivariate-regression-with-dummy-variables.html"><a href="multivariate-regression-with-dummy-variables.html#several-related-dummy-variables"><i class="fa fa-check"></i><b>14.1.1</b> Several related dummy variables</a></li>
<li class="chapter" data-level="14.1.2" data-path="multivariate-regression-with-dummy-variables.html"><a href="multivariate-regression-with-dummy-variables.html#dummy-variable-and-continuous-variable-in-regression"><i class="fa fa-check"></i><b>14.1.2</b> Dummy Variable and Continuous Variable in Regression</a></li>
<li class="chapter" data-level="14.1.3" data-path="multivariate-regression-with-dummy-variables.html"><a href="multivariate-regression-with-dummy-variables.html#interaction-terms-with-non-dummy-variables"><i class="fa fa-check"></i><b>14.1.3</b> Interaction terms with non-dummy variables</a></li>
<li class="chapter" data-level="14.1.4" data-path="multivariate-regression-with-dummy-variables.html"><a href="multivariate-regression-with-dummy-variables.html#f-test-for-differences-across-groups"><i class="fa fa-check"></i><b>14.1.4</b> F-test for differences across groups</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="15" data-path="formal-tests-on-assumptions.html"><a href="formal-tests-on-assumptions.html"><i class="fa fa-check"></i><b>15</b> Formal Tests on Assumptions</a>
<ul>
<li class="chapter" data-level="15.1" data-path="formal-tests-on-assumptions.html"><a href="formal-tests-on-assumptions.html#multicollinearity"><i class="fa fa-check"></i><b>15.1</b> Multicollinearity</a></li>
<li class="chapter" data-level="15.2" data-path="formal-tests-on-assumptions.html"><a href="formal-tests-on-assumptions.html#heteroscedasticity"><i class="fa fa-check"></i><b>15.2</b> Heteroscedasticity</a></li>
<li class="chapter" data-level="15.3" data-path="formal-tests-on-assumptions.html"><a href="formal-tests-on-assumptions.html#specification-errors"><i class="fa fa-check"></i><b>15.3</b> Specification Errors</a></li>
<li class="chapter" data-level="15.4" data-path="formal-tests-on-assumptions.html"><a href="formal-tests-on-assumptions.html#alternative-functional-forms"><i class="fa fa-check"></i><b>15.4</b> Alternative Functional Forms</a>
<ul>
<li class="chapter" data-level="15.4.1" data-path="formal-tests-on-assumptions.html"><a href="formal-tests-on-assumptions.html#log-log-model"><i class="fa fa-check"></i><b>15.4.1</b> Log-Log Model</a></li>
<li class="chapter" data-level="15.4.2" data-path="formal-tests-on-assumptions.html"><a href="formal-tests-on-assumptions.html#log-lin-model"><i class="fa fa-check"></i><b>15.4.2</b> Log-Lin Model</a></li>
<li class="chapter" data-level="15.4.3" data-path="formal-tests-on-assumptions.html"><a href="formal-tests-on-assumptions.html#lin-log-model"><i class="fa fa-check"></i><b>15.4.3</b> Lin-Log Model</a></li>
</ul></li>
<li class="chapter" data-level="15.5" data-path="formal-tests-on-assumptions.html"><a href="formal-tests-on-assumptions.html#practical-multivariate-dummy-regression-and-formal-tests-of-assumptions"><i class="fa fa-check"></i><b>15.5</b> Practical: Multivariate (Dummy) Regression and Formal Tests of Assumptions</a></li>
</ul></li>
<li class="chapter" data-level="16" data-path="additional-topics.html"><a href="additional-topics.html"><i class="fa fa-check"></i><b>16</b> Additional Topics</a>
<ul>
<li class="chapter" data-level="16.1" data-path="additional-topics.html"><a href="additional-topics.html#predicting-outcome-using-ols"><i class="fa fa-check"></i><b>16.1</b> Predicting Outcome using OLS</a>
<ul>
<li class="chapter" data-level="16.1.1" data-path="additional-topics.html"><a href="additional-topics.html#simulated-data"><i class="fa fa-check"></i><b>16.1.1</b> Simulated Data</a></li>
<li class="chapter" data-level="16.1.2" data-path="additional-topics.html"><a href="additional-topics.html#ols-1"><i class="fa fa-check"></i><b>16.1.2</b> OLS</a></li>
<li class="chapter" data-level="16.1.3" data-path="additional-topics.html"><a href="additional-topics.html#use-predict"><i class="fa fa-check"></i><b>16.1.3</b> Use <code>predict()</code></a></li>
<li class="chapter" data-level="16.1.4" data-path="additional-topics.html"><a href="additional-topics.html#extra-visualization"><i class="fa fa-check"></i><b>16.1.4</b> Extra: Visualization</a></li>
<li class="chapter" data-level="16.1.5" data-path="additional-topics.html"><a href="additional-topics.html#real-data"><i class="fa fa-check"></i><b>16.1.5</b> Real Data</a></li>
</ul></li>
<li class="chapter" data-level="16.2" data-path="additional-topics.html"><a href="additional-topics.html#designing-and-testing-a-survey"><i class="fa fa-check"></i><b>16.2</b> Designing and Testing a Survey</a>
<ul>
<li class="chapter" data-level="16.2.1" data-path="additional-topics.html"><a href="additional-topics.html#calculating-sample-size"><i class="fa fa-check"></i><b>16.2.1</b> Calculating Sample Size</a></li>
<li class="chapter" data-level="16.2.2" data-path="additional-topics.html"><a href="additional-topics.html#testing-survey-reliability---cronbachs-alpha"><i class="fa fa-check"></i><b>16.2.2</b> Testing Survey Reliability - Cronbach’s Alpha</a></li>
</ul></li>
<li class="chapter" data-level="16.3" data-path="additional-topics.html"><a href="additional-topics.html#panel-data-models-fixed-vs.-random-effects"><i class="fa fa-check"></i><b>16.3</b> Panel Data Models (Fixed vs. Random Effects)</a>
<ul>
<li class="chapter" data-level="16.3.1" data-path="additional-topics.html"><a href="additional-topics.html#simulated-panel-dataset"><i class="fa fa-check"></i><b>16.3.1</b> Simulated Panel Dataset</a></li>
<li class="chapter" data-level="16.3.2" data-path="additional-topics.html"><a href="additional-topics.html#fixed-effects-vs.-random-effects"><i class="fa fa-check"></i><b>16.3.2</b> Fixed Effects vs. Random Effects</a></li>
<li class="chapter" data-level="16.3.3" data-path="additional-topics.html"><a href="additional-topics.html#hausman-test"><i class="fa fa-check"></i><b>16.3.3</b> Hausman Test</a></li>
</ul></li>
<li class="chapter" data-level="16.4" data-path="additional-topics.html"><a href="additional-topics.html#lagged-values-and-preliminaries-in-forecasting"><i class="fa fa-check"></i><b>16.4</b> Lagged Values and Preliminaries in Forecasting</a>
<ul>
<li class="chapter" data-level="16.4.1" data-path="additional-topics.html"><a href="additional-topics.html#simulated-time-series"><i class="fa fa-check"></i><b>16.4.1</b> Simulated Time Series</a></li>
<li class="chapter" data-level="16.4.2" data-path="additional-topics.html"><a href="additional-topics.html#real-data-1"><i class="fa fa-check"></i><b>16.4.2</b> Real Data</a></li>
</ul></li>
<li class="chapter" data-level="16.5" data-path="additional-topics.html"><a href="additional-topics.html#the-end"><i class="fa fa-check"></i><b>16.5</b> The End!</a></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">LBOMETR Course Book</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="multivariate-regression-with-dummy-variables" class="section level1 hasAnchor" number="14">
<h1><span class="header-section-number">14</span> Multivariate Regression with Dummy Variables<a href="multivariate-regression-with-dummy-variables.html#multivariate-regression-with-dummy-variables" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div id="preliminaries-6" class="section level4 hasAnchor" number="14.0.0.1">
<h4><span class="header-section-number">14.0.0.1</span> Preliminaries<a href="multivariate-regression-with-dummy-variables.html#preliminaries-6" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<div class="sourceCode" id="cb332"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb332-1"><a href="multivariate-regression-with-dummy-variables.html#cb332-1" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb332-2"><a href="multivariate-regression-with-dummy-variables.html#cb332-2" tabindex="-1"></a><span class="fu">library</span>(lmtest)</span></code></pre></div>
<div class="sourceCode" id="cb333"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb333-1"><a href="multivariate-regression-with-dummy-variables.html#cb333-1" tabindex="-1"></a><span class="fu">library</span>(wooldridge) </span>
<span id="cb333-2"><a href="multivariate-regression-with-dummy-variables.html#cb333-2" tabindex="-1"></a><span class="fu">data</span>(wage1)</span>
<span id="cb333-3"><a href="multivariate-regression-with-dummy-variables.html#cb333-3" tabindex="-1"></a>sample1<span class="ot">&lt;-</span>wage1</span></code></pre></div>
</div>
<div id="dummy-variables" class="section level2 hasAnchor" number="14.1">
<h2><span class="header-section-number">14.1</span> Dummy Variables<a href="multivariate-regression-with-dummy-variables.html#dummy-variables" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<ul>
<li><p>Binary variables defined as 0 or 1;</p></li>
<li><p>D=1 if the criterion is satisfied</p></li>
<li><p>D=0 if not</p>
<ul>
<li><p>Convey qualitative info</p></li>
<li><p>Examples: female, married, graduated, passed</p></li>
<li><p>Example: variable female where female=1 for females, female=0 for males</p></li>
</ul></li>
<li><p>“gender” is not a good variable name because it is not clear if gender=1 for male or femal</p></li>
<li><p>Can be an independent variable or dependent variable in a probit/logit model</p></li>
</ul>
<table>
<colgroup>
<col width="50%" />
<col width="50%" />
</colgroup>
<thead>
<tr class="header">
<th>Code</th>
<th>Definition</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>data &lt;- data %&gt;% mutate(response_dummy = if_else(response == "yes", 1, 0))</code></td>
<td>This is when you generate a new variable in your dataset. You can change “yes” to female or married, etc.</td>
</tr>
<tr class="even">
<td><code>Dataset_CP_modified &lt;- Dataset_CP %&gt;%mutate(Q37a_HoursWeekChildren_level = case_when (Q37a_HoursWeekChildren &lt;= 5 ~ "low",Q37a_HoursWeekChildren &gt; 5 &amp; Q37a_HoursWeekChildren &lt;= 15 ~ "medium",Q37a_HoursWeekChildren &gt; 15 ~ "high"))</code></td>
<td>This is when you have numerous categories to represent dummy variables</td>
</tr>
</tbody>
</table>
<p>Regression Models:</p>
<p>wage = <span class="math inline">\(\beta_0\)</span> + <span class="math inline">\(\epsilon\)</span></p>
<p>Since there is only the intercept, there are no independent variables:</p>
<div class="sourceCode" id="cb334"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb334-1"><a href="multivariate-regression-with-dummy-variables.html#cb334-1" tabindex="-1"></a>null<span class="ot">&lt;-</span><span class="fu">lm</span>(wage<span class="sc">~</span><span class="dv">1</span>, <span class="at">data=</span>sample1)</span>
<span id="cb334-2"><a href="multivariate-regression-with-dummy-variables.html#cb334-2" tabindex="-1"></a><span class="fu">summary</span>(null)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = wage ~ 1, data = sample1)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -5.3661 -2.5661 -1.2461  0.9839 19.0839 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)    5.896      0.161   36.62   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 3.693 on 525 degrees of freedom</code></pre>
<p>This shows the average wage.</p>
<p>Now, let’s look at when the independent variable is represented by a binary variable (1,0)</p>
<p>wage = <span class="math inline">\(\beta_0\)</span> + <span class="math inline">\(\delta_0\)</span>female + <span class="math inline">\(\epsilon\)</span></p>
<ul>
<li><p>The coefficient is the difference in wage for females compared to males</p></li>
<li><p>This model has different intercepts for females (<span class="math inline">\(\beta_0\)</span>+ <span class="math inline">\(\delta_0\)</span>) and males <span class="math inline">\(\beta_0\)</span></p></li>
<li><p>The intercept for females is the average wage for females and the intercept for males is the average wage for males</p></li>
<li><p>The regression t-test for significance of the coefficient on female is identical to the t-test for significant differences in wage between the female group and the male group, with the same mean, t-statistic, and p-value.</p>
<div class="sourceCode" id="cb336"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb336-1"><a href="multivariate-regression-with-dummy-variables.html#cb336-1" tabindex="-1"></a>single<span class="ot">&lt;-</span><span class="fu">lm</span>(wage<span class="sc">~</span>sample1<span class="sc">$</span>female, <span class="at">data =</span> sample1)</span>
<span id="cb336-2"><a href="multivariate-regression-with-dummy-variables.html#cb336-2" tabindex="-1"></a><span class="fu">summary</span>(single)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = wage ~ sample1$female, data = sample1)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -5.5995 -1.8495 -0.9877  1.4260 17.8805 
## 
## Coefficients:
##                Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)      7.0995     0.2100  33.806  &lt; 2e-16 ***
## sample1$female  -2.5118     0.3034  -8.279 1.04e-15 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 3.476 on 524 degrees of freedom
## Multiple R-squared:  0.1157, Adjusted R-squared:  0.114 
## F-statistic: 68.54 on 1 and 524 DF,  p-value: 1.042e-15</code></pre></li>
</ul>
<p>We can plot the regression line;</p>
<div class="sourceCode" id="cb338"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb338-1"><a href="multivariate-regression-with-dummy-variables.html#cb338-1" tabindex="-1"></a>sample1 <span class="sc">%&gt;%</span> </span>
<span id="cb338-2"><a href="multivariate-regression-with-dummy-variables.html#cb338-2" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>female, <span class="at">y=</span>wage))<span class="sc">+</span></span>
<span id="cb338-3"><a href="multivariate-regression-with-dummy-variables.html#cb338-3" tabindex="-1"></a>  <span class="fu">geom_point</span>()<span class="sc">+</span></span>
<span id="cb338-4"><a href="multivariate-regression-with-dummy-variables.html#cb338-4" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method=</span><span class="st">&quot;lm&quot;</span>, <span class="at">se=</span><span class="cn">FALSE</span>)<span class="sc">+</span></span>
<span id="cb338-5"><a href="multivariate-regression-with-dummy-variables.html#cb338-5" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()<span class="sc">+</span></span>
<span id="cb338-6"><a href="multivariate-regression-with-dummy-variables.html#cb338-6" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x=</span><span class="st">&quot;Gender&quot;</span>, <span class="at">y=</span><span class="st">&quot;Wage&quot;</span>,</span>
<span id="cb338-7"><a href="multivariate-regression-with-dummy-variables.html#cb338-7" tabindex="-1"></a>       <span class="at">title=</span><span class="st">&quot;Scatter Plot with Regression Line&quot;</span>)</span></code></pre></div>
<pre><code>## `geom_smooth()` using formula = &#39;y ~ x&#39;</code></pre>
<p><img src="LBOMETR_Course_Book_files/figure-html/unnamed-chunk-218-1.png" width="672" /></p>
<p>The figure shows the slope <code>-2.51</code> and the intercepts: 7.10 and 4.59</p>
<p>Results:</p>
<table>
<thead>
<tr class="header">
<th>Variables</th>
<th>Wage</th>
<th>Wage</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>female</td>
<td></td>
<td><code>-2.51***</code></td>
</tr>
<tr class="even">
<td>intercept</td>
<td><code>5.90***</code></td>
<td><code>7.10***</code></td>
</tr>
</tbody>
</table>
<p>We introduced a female dummy variable (1=female, 0 otherwise (known as <strong>intercept dummy</strong>)</p>
<p>This specification says that the intercept (or the average difference in wages between females and males) is different.</p>
<p>Intercept, <span class="math inline">\(\beta_0\)</span> , measures the intercept of the default group (males) and <span class="math inline">\(\beta_0 + \delta_0\)</span> is the intercept for females</p>
<p><span class="math inline">\(\beta_0 = 5.90\)</span> is the average value of wage.</p>
<p><span class="math inline">\(\delta_0 = -2.51\)</span> is the effect of the indicator variable female on wage</p>
<ul>
<li><p>Females have 2.51 lower wages than males. The interpretation of the coefficient is with respect to the reference/base category of males</p></li>
<li><p>The intercept or average wage for males is <span class="math inline">\(\beta_0 = 7.10\)</span></p></li>
<li><p>The average wage for females is <span class="math inline">\(\beta_0+\delta_0 = 7.10 + (-2.51)=4.59\)</span></p></li>
</ul>
<div id="dummy-variable-trap" class="section level4 hasAnchor" number="14.1.0.1">
<h4><span class="header-section-number">14.1.0.1</span> Dummy variable trap<a href="multivariate-regression-with-dummy-variables.html#dummy-variable-trap" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<ul>
<li><p>This refers to the problem that not all categories can be included in the regression and one category needs to be left out, which is called a base or reference category.</p></li>
<li><p>For example, male and female cannot be both included in the regression because of perfect collinearity</p></li>
<li><p>Including male instead of female in the regression:</p>
<p>wage = <span class="math inline">\(\beta_0 + \delta_0(1 - male) + \epsilon\)</span> =</p></li>
<li><p>wage = (<span class="math inline">\(\beta_0 + \delta_0\)</span>) - <span class="math inline">\(\delta_0\)</span>male + <span class="math inline">\(\epsilon\)</span></p></li>
<li><p>The coefficient <span class="math inline">\(-\delta_0\)</span> on male has the same magnitude and significance, but opposite sign from the coefficient on female.</p></li>
<li><p>The intercept in the model with male is <span class="math inline">\((\beta_0+\delta_0)\)</span> , which can also be obtained from the model with female (average wage of females)</p></li>
<li><p>A regression can be estimated with both male and female but with no constant (this approach is not commonly used)</p>
<h3 id="interactions-with-another-dummy-variable" class="hasAnchor">Interactions with another dummy variable<a href="multivariate-regression-with-dummy-variables.html#interactions-with-another-dummy-variable" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Interaction term - multiply variable by dummy variable</p>
<ul>
<li>Interaction terms for variables <em>female</em> and <em>married</em> can be done in two different ways.</li>
</ul>
<ol style="list-style-type: decimal">
<li>include <em>female</em> and <em>married</em> and <code>female*married</code> in the regression</li>
</ol>
<p>wage = <span class="math inline">\(\beta_0 +\beta_1female+\beta_2married+\beta_3female*married+\epsilon\)</span></p>
<ol start="2" style="list-style-type: decimal">
<li>Create four categories: <code>female*single</code>, <code>male*single</code>, <code>female*married</code>, and <code>male*married</code>; include 3 of them in the regression model (<code>male*single</code> is the reference category).</li>
</ol></li>
<li><p><strong>Note:</strong> Choice of reference category depends on you but commonly, the most number of observations in the category is chosen.</p>
<div class="sourceCode" id="cb340"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb340-1"><a href="multivariate-regression-with-dummy-variables.html#cb340-1" tabindex="-1"></a>sample_modified <span class="ot">&lt;-</span> sample1 <span class="sc">%&gt;%</span></span>
<span id="cb340-2"><a href="multivariate-regression-with-dummy-variables.html#cb340-2" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">female_married =</span> <span class="fu">if_else</span>(female <span class="sc">==</span> <span class="dv">1</span> <span class="sc">&amp;</span> married <span class="sc">==</span> <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">0</span>), </span>
<span id="cb340-3"><a href="multivariate-regression-with-dummy-variables.html#cb340-3" tabindex="-1"></a>         <span class="at">male_single =</span> <span class="fu">if_else</span>(female <span class="sc">==</span> <span class="dv">0</span> <span class="sc">&amp;</span> married <span class="sc">==</span> <span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">0</span>),  </span>
<span id="cb340-4"><a href="multivariate-regression-with-dummy-variables.html#cb340-4" tabindex="-1"></a>         <span class="at">male_married =</span> <span class="fu">if_else</span>(female <span class="sc">==</span> <span class="dv">0</span> <span class="sc">&amp;</span> married <span class="sc">==</span> <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">0</span>),</span>
<span id="cb340-5"><a href="multivariate-regression-with-dummy-variables.html#cb340-5" tabindex="-1"></a>         <span class="at">female_single =</span> <span class="fu">if_else</span>(female<span class="sc">==</span><span class="dv">1</span> <span class="sc">&amp;</span> married <span class="sc">==</span> <span class="dv">0</span>, <span class="dv">1</span>,<span class="dv">0</span>))  </span>
<span id="cb340-6"><a href="multivariate-regression-with-dummy-variables.html#cb340-6" tabindex="-1"></a><span class="fu">head</span>(sample_modified)</span></code></pre></div>
<pre><code>##   wage educ exper tenure nonwhite female married numdep smsa northcen south west construc
## 1 3.10   11     2      0        0      1       0      2    1        0     0    1        0
## 2 3.24   12    22      2        0      1       1      3    1        0     0    1        0
## 3 3.00   11     2      0        0      0       0      2    0        0     0    1        0
## 4 6.00    8    44     28        0      0       1      0    1        0     0    1        0
## 5 5.30   12     7      2        0      0       1      1    0        0     0    1        0
## 6 8.75   16     9      8        0      0       1      0    1        0     0    1        0
##   ndurman trcommpu trade services profserv profocc clerocc servocc    lwage expersq tenursq
## 1       0        0     0        0        0       0       0       0 1.131402       4       0
## 2       0        0     0        1        0       0       0       1 1.175573     484       4
## 3       0        0     1        0        0       0       0       0 1.098612       4       0
## 4       0        0     0        0        0       0       1       0 1.791759    1936     784
## 5       0        0     0        0        0       0       0       0 1.667707      49       4
## 6       0        0     0        0        1       1       0       0 2.169054      81      64
##   female_married male_single male_married female_single
## 1              0           0            0             1
## 2              1           0            0             0
## 3              0           1            0             0
## 4              0           0            1             0
## 5              0           0            1             0
## 6              0           0            1             0</code></pre></li>
</ul>
<p>Regression model:</p>
<p><span class="math inline">\(wage = \beta_0+\beta_1femalesingle+\beta_2femalemarried+\beta_3malemarried+\epsilon\)</span></p>
<p>You need to drop the reference category variable which we already did when we dropped <code>malesingle</code></p>
<div class="sourceCode" id="cb342"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb342-1"><a href="multivariate-regression-with-dummy-variables.html#cb342-1" tabindex="-1"></a>interaction<span class="ot">&lt;-</span><span class="fu">lm</span>(wage<span class="sc">~</span>female_married<span class="sc">+</span>female_single<span class="sc">+</span>male_married, <span class="at">data=</span>sample_modified)</span>
<span id="cb342-2"><a href="multivariate-regression-with-dummy-variables.html#cb342-2" tabindex="-1"></a><span class="fu">summary</span>(interaction)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = wage ~ female_married + female_single + male_married, 
##     data = sample_modified)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -5.7530 -1.7327 -0.9973  1.2566 17.0184 
## 
## Coefficients:
##                Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)      5.1680     0.3614  14.299  &lt; 2e-16 ***
## female_married  -0.6021     0.4645  -1.296    0.195    
## female_single   -0.5564     0.4736  -1.175    0.241    
## male_married     2.8150     0.4363   6.451 2.53e-10 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 3.352 on 522 degrees of freedom
## Multiple R-squared:  0.181,  Adjusted R-squared:  0.1763 
## F-statistic: 38.45 on 3 and 522 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>Regression model:</p>
<p><span class="math inline">\(wage = \beta_0+\beta_1female+\beta_2married+\beta_3femalemarried+\epsilon\)</span></p>
<div class="sourceCode" id="cb344"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb344-1"><a href="multivariate-regression-with-dummy-variables.html#cb344-1" tabindex="-1"></a>int1<span class="ot">&lt;-</span><span class="fu">lm</span>(wage<span class="sc">~</span>female<span class="sc">+</span>married<span class="sc">+</span>female_married, <span class="at">data=</span>sample_modified)</span>
<span id="cb344-2"><a href="multivariate-regression-with-dummy-variables.html#cb344-2" tabindex="-1"></a><span class="fu">summary</span>(int1)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = wage ~ female + married + female_married, data = sample_modified)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -5.7530 -1.7327 -0.9973  1.2566 17.0184 
## 
## Coefficients:
##                Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)      5.1680     0.3614  14.299  &lt; 2e-16 ***
## female          -0.5564     0.4736  -1.175    0.241    
## married          2.8150     0.4363   6.451 2.53e-10 ***
## female_married  -2.8607     0.6076  -4.708 3.20e-06 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 3.352 on 522 degrees of freedom
## Multiple R-squared:  0.181,  Adjusted R-squared:  0.1763 
## F-statistic: 38.45 on 3 and 522 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>Let’s have pretty regression results table:</p>
<div class="sourceCode" id="cb346"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb346-1"><a href="multivariate-regression-with-dummy-variables.html#cb346-1" tabindex="-1"></a><span class="cf">if</span>(<span class="sc">!</span>(<span class="st">&quot;stargazer&quot;</span> <span class="sc">%in%</span> <span class="fu">installed.packages</span>()[,<span class="st">&quot;Package&quot;</span>])) <span class="fu">install.packages</span>(<span class="st">&quot;stargazer&quot;</span>)</span></code></pre></div>
<div class="sourceCode" id="cb347"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb347-1"><a href="multivariate-regression-with-dummy-variables.html#cb347-1" tabindex="-1"></a><span class="fu">library</span>(stargazer)</span>
<span id="cb347-2"><a href="multivariate-regression-with-dummy-variables.html#cb347-2" tabindex="-1"></a><span class="co"># Create a regression table</span></span>
<span id="cb347-3"><a href="multivariate-regression-with-dummy-variables.html#cb347-3" tabindex="-1"></a><span class="fu">stargazer</span>(null, interaction, int1, <span class="co">#regression</span></span>
<span id="cb347-4"><a href="multivariate-regression-with-dummy-variables.html#cb347-4" tabindex="-1"></a>          <span class="at">type =</span> <span class="st">&quot;text&quot;</span>, <span class="at">title =</span> <span class="st">&quot;Regression Results&quot;</span>,</span>
<span id="cb347-5"><a href="multivariate-regression-with-dummy-variables.html#cb347-5" tabindex="-1"></a>          <span class="at">dep.var.labels =</span> <span class="st">&quot;Wage&quot;</span>,</span>
<span id="cb347-6"><a href="multivariate-regression-with-dummy-variables.html#cb347-6" tabindex="-1"></a>          <span class="co">#covariate.labels = c(&quot;B1&quot;, &quot;B2&quot;, &quot;BN&quot;), label your independent variables</span></span>
<span id="cb347-7"><a href="multivariate-regression-with-dummy-variables.html#cb347-7" tabindex="-1"></a>          <span class="at">omit.stat =</span> <span class="fu">c</span>(<span class="st">&quot;f&quot;</span>, <span class="st">&quot;ser&quot;</span>), <span class="at">digits =</span> <span class="dv">3</span>) <span class="co"># Omits F-statistic and standard error from the table and sets decimal places to 3</span></span></code></pre></div>
<pre><code>## 
## Regression Results
## ============================================
##                     Dependent variable:     
##                -----------------------------
##                            Wage             
##                   (1)       (2)       (3)   
## --------------------------------------------
## female                              -0.556  
##                                     (0.474) 
##                                             
## married                            2.815*** 
##                                     (0.436) 
##                                             
## female_married            -0.602   -2.861***
##                           (0.464)   (0.608) 
##                                             
## female_single             -0.556            
##                           (0.474)           
##                                             
## male_married             2.815***           
##                           (0.436)           
##                                             
## Constant       5.896***  5.168***  5.168*** 
##                 (0.161)   (0.361)   (0.361) 
##                                             
## --------------------------------------------
## Observations      526       526       526   
## R2               0.000     0.181     0.181  
## Adjusted R2      0.000     0.176     0.176  
## ============================================
## Note:            *p&lt;0.1; **p&lt;0.05; ***p&lt;0.01</code></pre>
<p><strong>Interpretation of Results:</strong></p>
<p>Model 1: The baseline wage when all other variables are absent. The reference group is single males.</p>
<p>Model 2:</p>
<ul>
<li><p>Female, Single: <span class="math inline">\(-0.556\)</span> (not significant) –&gt; Single females earn 0.556 less than single males, but the result is not statistically significant.</p></li>
<li><p>Male, Married: <span class="math inline">\(2.815\)</span>*** –&gt; Married males earn 2.815 more than single males</p></li>
<li><p>Constant: <span class="math inline">\(5.168\)</span>*** –&gt; The wage for single males</p></li>
</ul>
<p>Model 3:</p>
<ul>
<li><p>Female: <span class="math inline">\(-0.556\)</span> (not significant) –&gt; Being female alone does not significantly impact wages</p></li>
<li><p>Married: <span class="math inline">\(2.815\)</span>*** –&gt; Being married increases wages</p></li>
<li><p>Female x Married Interaction: <span class="math inline">\(-2.861\)</span>*** –&gt; Being a married female results in a decrease of 2,861 on wages.</p></li>
<li><p>Constant: <span class="math inline">\(5.168\)</span>*** –&gt; The wage for single males</p></li>
</ul>
<p>Model Fit:</p>
<p>Model 1: No explanatory power</p>
<p>Model 2 and 3: The models explain 18.1% of the variation in wages.</p>
</div>
<div id="several-related-dummy-variables" class="section level3 hasAnchor" number="14.1.1">
<h3><span class="header-section-number">14.1.1</span> Several related dummy variables<a href="multivariate-regression-with-dummy-variables.html#several-related-dummy-variables" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ul>
<li><p>Regression with several related dummy variables needs to have one reference category.</p></li>
<li><p>For example: Dummies for regions: northcentral, south, west. So, east is the reference category. Thus, <span class="math inline">\(east = 1-northcentral-south-west\)</span></p>
<p><span class="math inline">\(wage = \beta_0+\beta_1northcentral+\beta_2south+\beta_3west+\epsilon\)</span></p>
<div class="sourceCode" id="cb349"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb349-1"><a href="multivariate-regression-with-dummy-variables.html#cb349-1" tabindex="-1"></a>reg1<span class="ot">&lt;-</span><span class="fu">lm</span>(wage<span class="sc">~</span>northcen<span class="sc">+</span>south<span class="sc">+</span>west, <span class="at">data=</span>sample_modified)</span>
<span id="cb349-2"><a href="multivariate-regression-with-dummy-variables.html#cb349-2" tabindex="-1"></a><span class="fu">summary</span>(reg1)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = wage ~ northcen + south + west, data = sample_modified)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -6.083 -2.387 -1.097  1.157 18.610 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)   6.3697     0.3380  18.848   &lt;2e-16 ***
## northcen     -0.6593     0.4651  -1.418   0.1569    
## south        -0.9828     0.4316  -2.277   0.0232 *  
## west          0.2436     0.5154   0.473   0.6366    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 3.671 on 522 degrees of freedom
## Multiple R-squared:  0.0175, Adjusted R-squared:  0.01185 
## F-statistic: 3.099 on 3 and 522 DF,  p-value: 0.02646</code></pre></li>
</ul>
<table>
<thead>
<tr class="header">
<th>Region</th>
<th>Average Wage</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Northcentral</td>
<td>5.71</td>
</tr>
<tr class="even">
<td>South</td>
<td>5.39</td>
</tr>
<tr class="odd">
<td>West</td>
<td>6.61</td>
</tr>
<tr class="even">
<td>East</td>
<td>6.37</td>
</tr>
</tbody>
</table>
<p>Wages in the south are 0.98 lower than wages in the east, and wages in the northcentral and west are not significantly different from those in the east region.</p>
</div>
<div id="dummy-variable-and-continuous-variable-in-regression" class="section level3 hasAnchor" number="14.1.2">
<h3><span class="header-section-number">14.1.2</span> Dummy Variable and Continuous Variable in Regression<a href="multivariate-regression-with-dummy-variables.html#dummy-variable-and-continuous-variable-in-regression" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p><span class="math inline">\(wage=\beta_0+\beta_1educ+\epsilon\)</span></p>
<p>This model has the same intercept and slope on education for females and males</p>
<p><span class="math inline">\(wage=\beta_0+\beta_1educ+\delta_0female+\epsilon\)</span></p>
<ul>
<li><p>The effect of female on wage = <span class="math inline">\(\delta_0\)</span></p></li>
<li><p>The same slope for females and males = <span class="math inline">\(\beta_1\)</span></p></li>
<li><p>Intercept for males = <span class="math inline">\(\beta_0\)</span></p></li>
<li><p>Intercept for females = <span class="math inline">\(\beta_0+\delta_0\)</span></p>
<div class="sourceCode" id="cb351"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb351-1"><a href="multivariate-regression-with-dummy-variables.html#cb351-1" tabindex="-1"></a>withedu<span class="ot">&lt;-</span><span class="fu">lm</span>(wage<span class="sc">~</span>educ<span class="sc">+</span>female, <span class="at">data=</span>sample_modified)</span>
<span id="cb351-2"><a href="multivariate-regression-with-dummy-variables.html#cb351-2" tabindex="-1"></a><span class="fu">summary</span>(withedu)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = wage ~ educ + female, data = sample_modified)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -5.9890 -1.8702 -0.6651  1.0447 15.4998 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  0.62282    0.67253   0.926    0.355    
## educ         0.50645    0.05039  10.051  &lt; 2e-16 ***
## female      -2.27336    0.27904  -8.147 2.76e-15 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 3.186 on 523 degrees of freedom
## Multiple R-squared:  0.2588, Adjusted R-squared:  0.256 
## F-statistic: 91.32 on 2 and 523 DF,  p-value: &lt; 2.2e-16</code></pre></li>
</ul>
<p>Results:</p>
<table>
<thead>
<tr class="header">
<th>Variables</th>
<th>wage</th>
<th>female dummy wage</th>
<th>male dummy wage</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>educ</td>
<td>0.54***</td>
<td>0.51***</td>
<td>0.51***</td>
</tr>
<tr class="even">
<td>female</td>
<td></td>
<td>-2.27***</td>
<td></td>
</tr>
<tr class="odd">
<td>male</td>
<td></td>
<td></td>
<td>2.27***</td>
</tr>
<tr class="even">
<td>Intercept</td>
<td>-0.91</td>
<td>0.62</td>
<td>-1.65**</td>
</tr>
</tbody>
</table>
<p>Plotting the graph:</p>
<div class="sourceCode" id="cb353"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb353-1"><a href="multivariate-regression-with-dummy-variables.html#cb353-1" tabindex="-1"></a><span class="fu">ggplot</span>(sample_modified, <span class="fu">aes</span>(<span class="at">x =</span> educ, <span class="at">y =</span> wage, <span class="at">color =</span> <span class="fu">as.factor</span>(female))) <span class="sc">+</span> <span class="co">#differentiates point by female</span></span>
<span id="cb353-2"><a href="multivariate-regression-with-dummy-variables.html#cb353-2" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb353-3"><a href="multivariate-regression-with-dummy-variables.html#cb353-3" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="at">formula =</span> y <span class="sc">~</span> x, <span class="at">se =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb353-4"><a href="multivariate-regression-with-dummy-variables.html#cb353-4" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">color =</span> <span class="st">&quot;Gender&quot;</span>) <span class="sc">+</span></span>
<span id="cb353-5"><a href="multivariate-regression-with-dummy-variables.html#cb353-5" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb353-6"><a href="multivariate-regression-with-dummy-variables.html#cb353-6" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">&quot;Regression of Wage on Education, Differentiated by Gender&quot;</span>)</span></code></pre></div>
<p><img src="LBOMETR_Course_Book_files/figure-html/unnamed-chunk-226-1.png" width="672" /></p>
</div>
<div id="interaction-terms-with-non-dummy-variables" class="section level3 hasAnchor" number="14.1.3">
<h3><span class="header-section-number">14.1.3</span> Interaction terms with non-dummy variables<a href="multivariate-regression-with-dummy-variables.html#interaction-terms-with-non-dummy-variables" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p><span class="math inline">\(wage=\beta_0+\beta_1educ+\delta_0female+\delta_1female*educ+\epsilon\)</span></p>
<ul>
<li><p>This model has different slopes on education and intercepts for females and males</p></li>
<li><p>slope for males = <span class="math inline">\(\beta_1\)</span></p></li>
<li><p>slope for females = <span class="math inline">\(\beta_1+\delta_1\)</span></p></li>
<li><p>intercept for males = <span class="math inline">\(\beta_0\)</span></p></li>
<li><p>intercept for females = <span class="math inline">\(\beta_0+\delta_0\)</span></p>
<div class="sourceCode" id="cb354"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb354-1"><a href="multivariate-regression-with-dummy-variables.html#cb354-1" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">lm</span>(wage <span class="sc">~</span> educ <span class="sc">+</span> female <span class="sc">+</span> female<span class="sc">:</span>educ, <span class="at">data =</span> sample_modified)</span>
<span id="cb354-2"><a href="multivariate-regression-with-dummy-variables.html#cb354-2" tabindex="-1"></a><span class="fu">summary</span>(model) <span class="co">#you can create interaction term when regressing by using &#39;:&#39;</span></span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = wage ~ educ + female + female:educ, data = sample_modified)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -6.1611 -1.8028 -0.6367  1.0054 15.5258 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  0.20050    0.84356   0.238    0.812    
## educ         0.53948    0.06422   8.400 4.24e-16 ***
## female      -1.19852    1.32504  -0.905    0.366    
## educ:female -0.08600    0.10364  -0.830    0.407    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 3.186 on 522 degrees of freedom
## Multiple R-squared:  0.2598, Adjusted R-squared:  0.2555 
## F-statistic: 61.07 on 3 and 522 DF,  p-value: &lt; 2.2e-16</code></pre></li>
</ul>
<p>Interpretation of Results:</p>
<ul>
<li><p>Slope for males is 0.54</p></li>
<li><p>Slope for females is 0.45</p></li>
<li><p>Intercept for males is 0.20</p></li>
<li><p>Intercept for females is <span class="math inline">\(-1.00\)</span></p></li>
<li><p>The coefficient on female and on the interaction term between female and education are not significant. So, the intercepts and the slopes of returns to education are not significantly different for females and males.</p></li>
</ul>
</div>
<div id="f-test-for-differences-across-groups" class="section level3 hasAnchor" number="14.1.4">
<h3><span class="header-section-number">14.1.4</span> F-test for differences across groups<a href="multivariate-regression-with-dummy-variables.html#f-test-for-differences-across-groups" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>F-test is used to test whether the returns to education, experience, and tenure are the same for two groups (males and females).</p>
<p><span class="math inline">\(H_0\)</span> : The coefficients on interaction terms are all zero, meaning that the impact of non-dummy variables on dependent variables is the same for the two groups.</p>
<p><span class="math inline">\(H_a\)</span> : At least one of the coefficients is not zero, meaning, the impact is different for the two groups.</p>
<p>Step 1: Fit the Full and Reduced Models</p>
<div class="sourceCode" id="cb356"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb356-1"><a href="multivariate-regression-with-dummy-variables.html#cb356-1" tabindex="-1"></a>full<span class="ot">&lt;-</span><span class="fu">lm</span>(wage<span class="sc">~</span>educ<span class="sc">+</span>exper<span class="sc">+</span>tenure<span class="sc">+</span>female<span class="sc">+</span>female<span class="sc">:</span>educ<span class="sc">+</span>female<span class="sc">:</span>exper<span class="sc">+</span>female<span class="sc">:</span>tenure, <span class="at">data=</span>sample_modified)</span></code></pre></div>
<p>This model includes interactiono terms, allowing the effects of continuous variables to be different for females.</p>
<div class="sourceCode" id="cb357"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb357-1"><a href="multivariate-regression-with-dummy-variables.html#cb357-1" tabindex="-1"></a>reduced<span class="ot">&lt;-</span><span class="fu">lm</span>(wage<span class="sc">~</span>educ<span class="sc">+</span>exper<span class="sc">+</span>tenure<span class="sc">+</span>female, <span class="at">data=</span>sample_modified)</span></code></pre></div>
<p>This model assumes education, experience, and tenure have the same impact for males and females but allows for general difference in wage levels through female coefficient.</p>
<p>Step 2: Perform the F-Test</p>
<div class="sourceCode" id="cb358"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb358-1"><a href="multivariate-regression-with-dummy-variables.html#cb358-1" tabindex="-1"></a>result<span class="ot">&lt;-</span><span class="fu">anova</span>(reduced,full)</span>
<span id="cb358-2"><a href="multivariate-regression-with-dummy-variables.html#cb358-2" tabindex="-1"></a><span class="fu">print</span>(result)</span></code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Model 1: wage ~ educ + exper + tenure + female
## Model 2: wage ~ educ + exper + tenure + female + female:educ + female:exper + 
##     female:tenure
##   Res.Df    RSS Df Sum of Sq      F    Pr(&gt;F)    
## 1    521 4557.3                                  
## 2    518 4394.2  3    163.06 6.4074 0.0002878 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>This compares the full and reduced model; If the p-value&lt;0.05, reject the null. In this case, Females have significantly different wages than males.</p>
</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="ordinary-least-squares.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="formal-tests-on-assumptions.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["LBOMETR_Course_Book.pdf", "LBOMETR_Course_Book.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "section",
"depth": 4
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
